name: Deploy new environment variables

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate file
        run: |
          touch .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.SERVER_PORT }}" >> .env

      - name: Deploy file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DCISM_HOST }}
          username: ${{ secrets.DCISM_USERNAME }}
          password: ${{ secrets.DCISM_PASSWORD }}
          port: ${{ secrets.DCISM_PORT }}
          source: ".env"
          target: "${{ secrets.DCISM_SUBDOMAIN }}"